const serverHost = 'http://localhost:9000/api/';
export function backEndLinks() {
    return{
        auth: serverHost+'auth/',
        refresh: serverHost+'auth/refresh/',
        user: serverHost+'user/',
        userProfile: serverHost+'user/profile/',
        userSearch: serverHost+'user/search/',
        userLog: serverHost+'user/log/',
        userLike: serverHost+'user/likes/',
        userRating: serverHost+'user/rating/',
        blog: serverHost+'blog/',
        blogGenre: serverHost+'blog/genre/',
        blogComment: serverHost+'blog/comment/',
        blogReaction: serverHost+'blog/reaction/',
        blogView: serverHost+'blog/view/',
        blogCommentReaction: serverHost+'blog/comment-reaction/',
        blogCommentReply: serverHost+'blog/comment-reply/',
        forum: serverHost+'forum/',
        forumTag: serverHost+'forum/tag/',
        forumTopic: serverHost+'forum/topic/',
        forumComment: serverHost+'forum/comment/',
        forumView: serverHost+'forum/view/',
        forumCommentReaction: serverHost+'forum/comment-reaction/',
        forumCommentReply: serverHost+'forum/comment-reply/',
        pageSettingImage: serverHost+'page-setting/images/',
        pageSettingSocial: serverHost+'page-setting/socials/',
        pageSettingContact: serverHost+'page-setting/contact/',
        passwordReset: serverHost+'password-reset/',
        store: serverHost+'store/',
        storeGenre: serverHost+'store/genre/',
        storeType: serverHost+'store/type/',
        storeReaction: serverHost+'store/reaction/',
        storeView: serverHost+'store/view/',
        storeRating: serverHost+'store/rating/',
        storeDownload: serverHost+'store/download/',
        storeCapture: serverHost+'store/capture/',
        storeHighlight: serverHost+'store/highlight/',
        passwordChange: serverHost+'password-change/',
    }
}
